[package]
name = "ml-practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ml_practice"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
pyo3 = "0.22.2"
rand = "0.8.5"
