[project]
name = "ml-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.114.0",
    "pydantic>=2.9.1",
]

[project.scripts]
run_ml_api = "ml_api.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
