[package]
name = "rs_algos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rs_algos"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
pyo3 = { version = "0.22.2", features = ["anyhow"] }
rand = "0.8.5"
