name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  CI:
    name: CI workflow for workspace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Format
        run: uv run ruff format src packages
      - name: Lint
        run: uv run ruff check --output-format=github src packages
      - name: Type check
        run: uv run mypy src packages
      - name: Run tests
        run: uv run pytest tests
